//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apimvcproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Görevli
    {
        public int görevliID { get; set; }
        public string görevliAdi { get; set; }
        public Nullable<bool> görevliCinsiyet { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string Unvan { get; set; }
    }
}
