//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apimvcproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manavlar
    {
        public int manavID { get; set; }
        public string manavAdi { get; set; }
        public string manavAdres { get; set; }
    }
}
