//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apimvcproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meyveler
    {
        public int meyveID { get; set; }
        public string meyveAdi { get; set; }
        public Nullable<System.DateTime> meyveSonKullanma { get; set; }
        public string meyveAdres { get; set; }
        public string meyveStok { get; set; }
    }
}
