//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apimvcproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sebzeler
    {
        public int sebzeID { get; set; }
        public string sebzeAdi { get; set; }
        public Nullable<System.DateTime> sebzeSonKullanma { get; set; }
        public string sebzeAdres { get; set; }
        public string sebzeStok { get; set; }
    }
}
